name: Main Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: cd frontend && npm install 
      - name: Build
        run: cd frontend && npm run build 
      - name: Linter
        run: cd frontend && npm run lint